### ISSUE TITLE
ファイル添付機能

### ISSUE THREAD

**Issue by yamashita** [ysugimoto/Terrier#15]
ファイルアップロードは正常動作するようですが、PHPMail, SMTP, で送信するメールにはファイル添付するロジックってありますか？
Terrier\Driver\Mail\Driverのattache() が呼ばれる箇所がない気が。

**Comment by ysugimoto** [comment]
ファイルの取り回しに対して色々考慮しないといけないことがあるため、現在未実装となっています。

- アップロードされたファイルは一時的にどこに保持するべきか（利用される環境によってはドキュメントルート内に置かないといけなくて、セキュリティ担保ができないため
- ファイルを永続的に保持すべきかどうか。
- MimeType判定や実行ファイルなどのブロックが必要。

添付機能自体は実装してあると思います。。。

**Comment by yamashita** [comment]
了解いたしました。
添付機能自体は既存のものをうまく呼び出せば問題なく動作したのと
ご指摘の点は利用用途によって適宜実装、ということで問題ありませんでした。
ご回答ありがとうございます。コードが綺麗で助かりました。
